spring:
  application:
    name: okayokya-cloud-zuul-api-gateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-user:
      path: /api/user-service/**
      serviceId: okayokya-cloud-service-user
